name: Digger Workflow
on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: digger run
        uses: diggerhq/digger@v0.4.13
        with:
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::176207359176:role/github-actions-GitHubActionsServiceRole-BwQR0UB8GquE
          aws-region: us-east-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}