name: Terraform Plan Workflow
on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      statuses: write

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::176207359176:role/github-actions-GitHubActionsServiceRole-BwQR0UB8GquE
          aws-region: us-east-1

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        working-directory: organization
        run: terraform init

      - name: Run Terraform Plan
        id: plan
        working-directory: organization
        run: terraform plan -no-color > ../tfplan.txt

      - name: Output Terraform Plan
        run: cat tfplan.txt

      - name: Post PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "### Terraform Plan Results"
          message: |
            $(cat tfplan.txt)
